Repository Ultreon/ultracraft, pull requests merged in 2023-10, with the labels that each got.

#46 Better noise settings
  core/src/main/java/com/ultreon/craft/UltreonCraft.java
  core/src/main/java/com/ultreon/craft/render/ItemRenderer.java
  core/src/main/java/com/ultreon/craft/world/gen/BiomeGenerator.java
  core/src/main/java/com/ultreon/craft/world/gen/noise/DomainWarping.java
  core/src/main/java/com/ultreon/craft/world/gen/noise/NoiseInstance.java
  core/src/main/java/com/ultreon/craft/world/gen/noise/NoiseSettings.java
  core/src/main/java/com/ultreon/craft/world/gen/noise/NoiseSettingsInit.java
  core/src/main/java/com/ultreon/craft/world/gen/noise/NoiseUtils.java
Labels: enhancement

#16 Mining
  .circleci/config.yml
  core/src/main/java/com/ultreon/craft/BlockModelRegistry.java
  core/src/main/java/com/ultreon/craft/PollingExecutorService.java
  core/src/main/java/com/ultreon/craft/UltreonCraft.java
  core/src/main/java/com/ultreon/craft/block/Block.java
  core/src/main/java/com/ultreon/craft/block/Blocks.java
  core/src/main/java/com/ultreon/craft/debug/Debugger.java
  core/src/main/java/com/ultreon/craft/entity/Entity.java
  core/src/main/java/com/ultreon/craft/entity/Player.java
  core/src/main/java/com/ultreon/craft/events/ItemEvents.java
  core/src/main/java/com/ultreon/craft/input/DesktopInput.java
  core/src/main/java/com/ultreon/craft/input/GameInput.java
  core/src/main/java/com/ultreon/craft/item/BlockItem.java
  core/src/main/java/com/ultreon/craft/item/Item.java
  core/src/main/java/com/ultreon/craft/item/Items.java
  core/src/main/java/com/ultreon/craft/item/UseItemContext.java
  core/src/main/java/com/ultreon/craft/item/material/ItemMaterial.java
  core/src/main/java/com/ultreon/craft/item/material/ItemMaterials.java
  core/src/main/java/com/ultreon/craft/item/tool/PickaxeItem.java
  core/src/main/java/com/ultreon/craft/item/tool/ToolItem.java
  core/src/main/java/com/ultreon/craft/item/tool/ToolType.java
  core/src/main/java/com/ultreon/craft/render/DebugRenderer.java
  core/src/main/java/com/ultreon/craft/render/Shaders.java
  core/src/main/java/com/ultreon/craft/render/WorldRenderer.java
  core/src/main/java/com/ultreon/craft/render/gui/screens/WorldLoadScreen.java
  core/src/main/java/com/ultreon/craft/render/model/BakedCubeModel.java
  core/src/main/java/com/ultreon/craft/render/world/WorldRenderer.java
  core/src/main/java/com/ultreon/craft/util/HitResult.java
  core/src/main/java/com/ultreon/craft/util/WorldRayCaster.java
  core/src/main/java/com/ultreon/craft/world/BiomeSelectionHelper.java
  core/src/main/java/com/ultreon/craft/world/Chunk.java
  core/src/main/java/com/ultreon/craft/world/Section.java
  core/src/main/java/com/ultreon/craft/world/World.java
  core/src/main/java/com/ultreon/craft/world/gen/TerrainGenerator.java
  core/src/main/resources/assets/craft/shaders/mining.frag
  core/src/main/resources/assets/craft/shaders/mining.vert
  core/src/main/resources/assets/craft/textures/break_stages.png
  core/src/main/resources/assets/craft/textures/misc/breaking1.png
  core/src/main/resources/assets/craft/textures/misc/breaking2.png
  core/src/main/resources/assets/craft/textures/misc/breaking3.png
  core/src/main/resources/assets/craft/textures/misc/breaking4.png
  core/src/main/resources/assets/craft/textures/misc/breaking5.png
  core/src/main/resources/assets/craft/textures/misc/breaking6.png
Labels: enhancement

#15 Items
  .circleci/config.yml
  core/src/main/java/com/ultreon/craft/BlockModelRegistry.java
  core/src/main/java/com/ultreon/craft/PollingExecutorService.java
  core/src/main/java/com/ultreon/craft/TextureManager.java
  core/src/main/java/com/ultreon/craft/UltreonCraft.java
  core/src/main/java/com/ultreon/craft/block/Block.java
  core/src/main/java/com/ultreon/craft/block/Blocks.java
  core/src/main/java/com/ultreon/craft/debug/Debugger.java
  core/src/main/java/com/ultreon/craft/entity/Entity.java
  core/src/main/java/com/ultreon/craft/entity/Player.java
  core/src/main/java/com/ultreon/craft/events/ItemEvents.java
  core/src/main/java/com/ultreon/craft/input/DesktopInput.java
  core/src/main/java/com/ultreon/craft/input/GameInput.java
  core/src/main/java/com/ultreon/craft/item/BlockItem.java
  core/src/main/java/com/ultreon/craft/item/Item.java
  core/src/main/java/com/ultreon/craft/item/Items.java
  core/src/main/java/com/ultreon/craft/item/UseItemContext.java
  core/src/main/java/com/ultreon/craft/item/material/ItemMaterial.java
  core/src/main/java/com/ultreon/craft/item/material/ItemMaterials.java
  core/src/main/java/com/ultreon/craft/item/tool/PickaxeItem.java
  core/src/main/java/com/ultreon/craft/item/tool/ShovelItem.java
  core/src/main/java/com/ultreon/craft/item/tool/ToolItem.java
  core/src/main/java/com/ultreon/craft/item/tool/ToolType.java
  core/src/main/java/com/ultreon/craft/registry/Registries.java
  core/src/main/java/com/ultreon/craft/render/DebugRenderer.java
  core/src/main/java/com/ultreon/craft/render/Hud.java
  core/src/main/java/com/ultreon/craft/render/ItemRenderer.java
  core/src/main/java/com/ultreon/craft/render/Renderer.java
  core/src/main/java/com/ultreon/craft/render/Shaders.java
  core/src/main/java/com/ultreon/craft/render/WorldRenderer.java
  core/src/main/java/com/ultreon/craft/render/gui/screens/ItemRenderTestScreen.java
  core/src/main/java/com/ultreon/craft/render/gui/screens/WorldLoadScreen.java
  core/src/main/java/com/ultreon/craft/render/model/BakedCubeModel.java
  core/src/main/java/com/ultreon/craft/render/texture/atlas/TextureAtlas.java
  core/src/main/java/com/ultreon/craft/render/world/WorldRenderer.java
  core/src/main/java/com/ultreon/craft/util/HitResult.java
  core/src/main/java/com/ultreon/craft/util/WorldRayCaster.java
  core/src/main/java/com/ultreon/craft/world/BiomeSelectionHelper.java
  core/src/main/java/com/ultreon/craft/world/Chunk.java
  core/src/main/java/com/ultreon/craft/world/Section.java
  core/src/main/java/com/ultreon/craft/world/World.java
  core/src/main/java/com/ultreon/craft/world/gen/TerrainGenerator.java
  core/src/main/resources/assets/craft/languages/en_us.json
  core/src/main/resources/assets/craft/shaders/mining.frag
  core/src/main/resources/assets/craft/shaders/mining.vert
  core/src/main/resources/assets/craft/textures/break_stages.png
  core/src/main/resources/assets/craft/textures/items.png
  core/src/main/resources/assets/craft/textures/items/wooden_pickaxe.png
  core/src/main/resources/assets/craft/textures/items/wooden_shovel.png
  core/src/main/resources/assets/craft/textures/items/wooden_shovel.xcf
  core/src/main/resources/assets/craft/textures/misc/breaking1.png
  core/src/main/resources/assets/craft/textures/misc/breaking2.png
  core/src/main/resources/assets/craft/textures/misc/breaking3.png
  core/src/main/resources/assets/craft/textures/misc/breaking4.png
  core/src/main/resources/assets/craft/textures/misc/breaking5.png
  core/src/main/resources/assets/craft/textures/misc/breaking6.png
Labels: enhancement

#36 Loading and Splash screens
  android/build.gradle
  android/src/com/ultreon/craft/AndroidLauncher.java
  asset-src/builtin-mods/java.pdn
  asset-src/builtin-mods/java.png
  build.gradle.kts
  build.gradle.old
  core/build.gradle
  core/src/main/java/com/ultreon/craft/Resizer.java
  core/src/main/java/com/ultreon/craft/Task.java
  core/src/main/java/com/ultreon/craft/TextureManager.java
  core/src/main/java/com/ultreon/craft/UltreonCraft.java
  core/src/main/java/com/ultreon/craft/input/DesktopInput.java
  core/src/main/java/com/ultreon/craft/input/GameInput.java
  core/src/main/java/com/ultreon/craft/input/MobileInput.java
  core/src/main/java/com/ultreon/craft/render/Drawable.java
  core/src/main/java/com/ultreon/craft/render/Hud.java
  core/src/main/java/com/ultreon/craft/render/Renderer.java
  core/src/main/java/com/ultreon/craft/render/WorldRenderer.java
  core/src/main/java/com/ultreon/craft/render/gui/LoadingOverlay.java
  core/src/main/java/com/ultreon/craft/render/gui/Widget.java
  core/src/main/java/com/ultreon/craft/render/model/CubeModel.java
  core/src/main/java/com/ultreon/craft/render/texture/atlas/TextureStitcher.java
  core/src/main/java/com/ultreon/craft/world/WorldRegion.java
  core/src/main/resources/assets/craft/libgdx_logo.png
  core/src/main/resources/assets/craft/logo.png
  core/src/main/resources/assets/craft/sounds/logo_reveal.mp3
  core/src/main/resources/assets/craft/textures/gui/loading_overlay_bg.png
  core/src/main/resources/assets/craft/textures/java_icon.png
  desktop/build.gradle
  desktop/src/main/java/com/ultreon/craft/DesktopPlatform.java
Labels: enhancement

#47 Inter-chunk meshes, and water rendering!
  core/src/main/java/com/ultreon/craft/render/DebugRenderer.java
  core/src/main/java/com/ultreon/craft/render/gui/screens/WorldLoadScreen.java
  core/src/main/java/com/ultreon/craft/render/world/ChunkMeshBuilder.java
  core/src/main/java/com/ultreon/craft/render/world/WorldRenderer.java
  core/src/main/java/com/ultreon/craft/world/Chunk.java
  core/src/main/java/com/ultreon/craft/world/World.java
  core/src/main/java/com/ultreon/craft/world/WorldRegion.java
  core/src/main/java/com/ultreon/craft/world/gen/BiomeGenerator.java
  core/src/main/java/com/ultreon/craft/world/gen/noise/DomainWarping.java
  core/src/main/java/com/ultreon/craft/world/gen/noise/NoiseUtils.java
  core/src/main/java/com/ultreon/craft/world/gen/noise/SimplexNoise.java
  core/src/main/resources/assets/craft/textures/blocks/water.png
  core/src/main/resources/assets/craft/textures/blocks/water.xcf
Labels: enhancement, development

#48 Fix scrolling in selection screen.
  core/src/main/java/com/ultreon/craft/input/DesktopInput.java
  core/src/main/java/com/ultreon/craft/render/gui/GuiContainer.java
  core/src/main/java/com/ultreon/craft/render/gui/screens/LanguageScreen.java
  core/src/main/java/com/ultreon/craft/render/gui/widget/SelectionList.java
Labels: bug

#49 🎒 Inventory and item stacks
  core/src/main/java/com/ultreon/craft/UltreonCraft.java
  core/src/main/java/com/ultreon/craft/block/Block.java
  core/src/main/java/com/ultreon/craft/block/Blocks.java
  core/src/main/java/com/ultreon/craft/entity/Player.java
  core/src/main/java/com/ultreon/craft/events/PlayerEvents.java
  core/src/main/java/com/ultreon/craft/input/DesktopInput.java
  core/src/main/java/com/ultreon/craft/input/GameInput.java
  core/src/main/java/com/ultreon/craft/item/BlockItem.java
  core/src/main/java/com/ultreon/craft/item/Item.java
  core/src/main/java/com/ultreon/craft/item/ItemStack.java
  core/src/main/java/com/ultreon/craft/item/Items.java
  core/src/main/java/com/ultreon/craft/item/UseItemContext.java
  core/src/main/java/com/ultreon/craft/item/tool/PickaxeItem.java
  core/src/main/java/com/ultreon/craft/item/tool/ShovelItem.java
  core/src/main/java/com/ultreon/craft/item/tool/ToolItem.java
  core/src/main/java/com/ultreon/craft/menu/ContainerMenu.java
  core/src/main/java/com/ultreon/craft/menu/Inventory.java
  core/src/main/java/com/ultreon/craft/menu/ItemSlot.java
  core/src/main/java/com/ultreon/craft/render/Hud.java
  core/src/main/java/com/ultreon/craft/render/ItemRenderer.java
  core/src/main/java/com/ultreon/craft/render/Renderer.java
  core/src/main/java/com/ultreon/craft/render/gui/Notifications.java
  core/src/main/java/com/ultreon/craft/render/gui/screens/Screen.java
  core/src/main/java/com/ultreon/craft/render/gui/screens/container/ContainerScreen.java
  core/src/main/java/com/ultreon/craft/render/gui/screens/container/InventoryScreen.java
  core/src/main/java/com/ultreon/craft/render/world/WorldRenderer.java
  core/src/main/java/com/ultreon/craft/world/Chunk.java
  core/src/main/java/com/ultreon/craft/world/World.java
  core/src/main/resources/assets/craft/languages/en_us.json
  core/src/main/resources/assets/craft/textures/gui/container/inventory.png
  core/src/main/resources/assets/craft/textures/gui/container/inventory.xcf
  core/src/main/resources/assets/craft/textures/gui/widgets.png
  core/src/main/resources/assets/craft/textures/gui/widgets.xcf
  desktop/src/main/java/com/ultreon/craft/desktop/client/gui/screen/ModListScreen.java
  gradle.properties
Labels: enhancement

#51 Create pl_pl.json
  core/src/main/resources/assets/craft/languages/pl_pl.json
Labels: language
